using System.Globalization;
using System.Reflection;
using ApiLoadTester.Core.Models;
using PdfSharp.Drawing;
using PdfSharp.Fonts;
using PdfSharp.Pdf;

namespace ApiLoadTester.Reporting;

/// <summary>Builds the customer-facing capacity report PDF: cover, executive summary, test
/// configuration/methodology, results overview, charts, error breakdown, and an appendix.</summary>
public sealed class PdfReportBuilder
{
    private static readonly HashSet<string> SensitiveHeaderNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "Authorization", "X-Api-Key", "Api-Key", "Cookie", "Set-Cookie", "X-Auth-Token", "Proxy-Authorization"
    };

    static PdfReportBuilder()
    {
        // PdfSharp 6 requires an explicit font source; see WindowsFontResolver for why we resolve
        // fonts ourselves instead of relying on PdfSharp's built-in Windows resolution.
        GlobalFontSettings.FontResolver ??= new WindowsFontResolver();
    }

    public void Save(TestSummary summary, string outputPath)
    {
        // Reports go to customers who may be anywhere; render numbers/dates in a fixed, predictable
        // format (en-US conventions) rather than whatever locale happens to be set on this machine.
        var previousCulture = CultureInfo.CurrentCulture;
        CultureInfo.CurrentCulture = ReportCulture;
        try
        {
            SaveCore(summary, outputPath);
        }
        finally
        {
            CultureInfo.CurrentCulture = previousCulture;
        }
    }

    private static readonly CultureInfo ReportCulture = CultureInfo.GetCultureInfo("en-US");

    private void SaveCore(TestSummary summary, string outputPath)
    {
        using var document = new PdfDocument();
        document.Info.Title = summary.Configuration.ReportTitle ?? "API Load Test Report";
        document.Info.Author = Environment.UserName;
        document.Info.Subject = "API capacity / load test results";

        var ctx = new PdfReportContext { Document = document };
        ctx.NewPage();

        DrawCoverPage(ctx, summary);

        ctx.NewPage();
        DrawExecutiveSummary(ctx, summary);
        DrawTestConfiguration(ctx, summary);
        DrawResultsOverview(ctx, summary);

        if (summary.RawResults.Count > 0)
        {
            DrawChartSection(ctx, "Throughput Over Time", ChartImageRenderer.RenderThroughputChart(summary));
            DrawChartSection(ctx, "Latency Over Time", ChartImageRenderer.RenderLatencyChart(summary));
        }

        if (summary.ErrorCount > 0)
            DrawErrorBreakdown(ctx, summary);

        DrawAppendix(ctx, summary);

        // DrawPageFooters re-opens each page's XGraphics in Append mode; the context's own graphics
        // object for the last page must be released first or PdfSharp throws.
        ctx.Gfx.Dispose();
        DrawPageFooters(document);

        document.Save(outputPath);
    }

    private static void DrawCoverPage(PdfReportContext ctx, TestSummary summary)
    {
        var titleFont = ReportFonts.Bold(26);
        var subtitleFont = ReportFonts.Regular(14);
        var labelFont = ReportFonts.Bold(10);
        var valueFont = ReportFonts.Regular(10);

        ctx.CursorY = 160;
        ctx.Gfx.DrawString(summary.Configuration.ReportTitle ?? "API Load Test Report", titleFont, PdfTheme.PrimaryBrush,
            new XRect(ctx.MarginLeft, ctx.CursorY, ctx.ContentWidth, 40), XStringFormats.TopLeft);
        ctx.CursorY += 44;

        if (!string.IsNullOrWhiteSpace(summary.Configuration.CustomerName))
        {
            ctx.Gfx.DrawString($"Prepared for {summary.Configuration.CustomerName}", subtitleFont, PdfTheme.MutedBrush,
                new XRect(ctx.MarginLeft, ctx.CursorY, ctx.ContentWidth, 24), XStringFormats.TopLeft);
            ctx.CursorY += 40;
        }
        else
        {
            ctx.CursorY += 16;
        }

        ctx.Gfx.DrawLine(new XPen(PdfTheme.Primary, 2), ctx.MarginLeft, ctx.CursorY, ctx.MarginLeft + ctx.ContentWidth, ctx.CursorY);
        ctx.CursorY += 24;

        DrawLabelValueRow(ctx, labelFont, valueFont, "Target endpoint", summary.Configuration.TargetUrl);
        DrawLabelValueRow(ctx, labelFont, valueFont, "HTTP method", summary.Configuration.HttpMethod);
        DrawLabelValueRow(ctx, labelFont, valueFont, "Test date", summary.StartedAt.ToLocalTime().ToString("f"));
        DrawLabelValueRow(ctx, labelFont, valueFont, "Duration", FormatDuration(summary.WallClockDuration));
        DrawLabelValueRow(ctx, labelFont, valueFont, "Concurrency", summary.Configuration.Concurrency.ToString());
        DrawLabelValueRow(ctx, labelFont, valueFont, "Generated by", $"{Environment.UserName} using API Load Tester {AppVersion()}");

        var noteFont = ReportFonts.Italic(9);
        var noteLines = WrapText(ctx.Gfx,
            "This report summarizes a single-endpoint constant-load capacity test. See the Methodology " +
            "appendix for scope and interpretation notes.",
            noteFont, ctx.ContentWidth);

        ctx.CursorY = ctx.Page.Height.Point - 90;
        foreach (var line in noteLines)
        {
            ctx.Gfx.DrawString(line, noteFont, PdfTheme.MutedBrush, new XRect(ctx.MarginLeft, ctx.CursorY, ctx.ContentWidth, 13), XStringFormats.TopLeft);
            ctx.CursorY += 13;
        }
    }

    private static void DrawLabelValueRow(PdfReportContext ctx, XFont labelFont, XFont valueFont, string label, string value)
    {
        ctx.Gfx.DrawString(label, labelFont, PdfTheme.BodyBrush, new XRect(ctx.MarginLeft, ctx.CursorY, 140, 18), XStringFormats.TopLeft);
        ctx.Gfx.DrawString(value, valueFont, PdfTheme.BodyBrush, new XRect(ctx.MarginLeft + 145, ctx.CursorY, ctx.ContentWidth - 145, 18), XStringFormats.TopLeft);
        ctx.CursorY += 22;
    }

    private static void DrawExecutiveSummary(PdfReportContext ctx, TestSummary summary)
    {
        DrawSectionHeading(ctx, "Executive Summary");

        var sentence =
            $"Against {summary.Configuration.Concurrency} concurrent virtual users, the target endpoint sustained " +
            $"{summary.OverallRequestsPerSecond:0.#} requests/second over {FormatDuration(summary.WallClockDuration)}, " +
            $"with a {summary.SuccessRate:P1} success rate and a 95th-percentile latency of {summary.Latency.P95Ms:0.#} ms.";

        var bodyFont = ReportFonts.Regular(10.5);
        var lines = WrapText(ctx.Gfx, sentence, bodyFont, ctx.ContentWidth);
        ctx.EnsureSpace((lines.Count * 15) + 8);
        foreach (var line in lines)
        {
            ctx.Gfx.DrawString(line, bodyFont, PdfTheme.BodyBrush, new XRect(ctx.MarginLeft, ctx.CursorY, ctx.ContentWidth, 15), XStringFormats.TopLeft);
            ctx.CursorY += 15;
        }
        ctx.CursorY += 8;

        DrawKpiStrip(ctx, [
            ("Total Requests", summary.TotalRequests.ToString("N0")),
            ("Success Rate", summary.SuccessRate.ToString("P1")),
            ("Throughput", $"{summary.OverallRequestsPerSecond:0.#} req/s"),
            ("P95 Latency", $"{summary.Latency.P95Ms:0.#} ms"),
            ("P99 Latency", $"{summary.Latency.P99Ms:0.#} ms"),
            ("Error Rate", (1 - summary.SuccessRate).ToString("P1"))
        ]);
    }

    private static void DrawKpiStrip(PdfReportContext ctx, (string Label, string Value)[] kpis)
    {
        const double tileHeight = 54;
        ctx.EnsureSpace(tileHeight + 10);

        var tileWidth = ctx.ContentWidth / kpis.Length;
        var labelFont = ReportFonts.Regular(8.5);
        var valueFont = ReportFonts.Bold(14);

        for (var i = 0; i < kpis.Length; i++)
        {
            var x = ctx.MarginLeft + (i * tileWidth);
            var rect = new XRect(x, ctx.CursorY, tileWidth - 6, tileHeight);
            ctx.Gfx.DrawRectangle(new XSolidBrush(PdfTheme.RowAlt), rect);
            ctx.Gfx.DrawString(kpis[i].Value, valueFont, PdfTheme.PrimaryBrush,
                new XRect(rect.X + 8, rect.Y + 8, rect.Width - 16, 22), XStringFormats.TopLeft);
            ctx.Gfx.DrawString(kpis[i].Label, labelFont, PdfTheme.MutedBrush,
                new XRect(rect.X + 8, rect.Y + 32, rect.Width - 16, 16), XStringFormats.TopLeft);
        }

        ctx.CursorY += tileHeight + 16;
    }

    private static void DrawTestConfiguration(PdfReportContext ctx, TestSummary summary)
    {
        DrawSectionHeading(ctx, "Test Configuration & Methodology");
        var config = summary.Configuration;

        if (!config.Tls.ValidateServerCertificate)
        {
            DrawWarningBanner(ctx, "Server certificate validation was DISABLED for this run. Results were not " +
                                     "obtained against a fully validated TLS chain and should not be used to " +
                                     "represent a production security posture.");
        }

        var rows = new List<string[]>
        {
            new[] { "Target URL", config.TargetUrl },
            new[] { "HTTP method", config.HttpMethod },
            new[] { "Concurrency (virtual users)", config.Concurrency.ToString() },
            new[] { "Duration", config.Duration.HasValue ? FormatDuration(config.Duration.Value) : "(request-count bound)" },
            new[] { "Max request count", config.MaxRequestCount?.ToString("N0") ?? "(duration bound)" },
            new[] { "Per-request timeout", $"{config.RequestTimeout.TotalSeconds:0.#} s" },
            new[] { "Ramp-in delay per worker", $"{config.RampInDelay.TotalMilliseconds:0.#} ms" },
            new[] { "Minimum TLS protocol", config.Tls.MinimumProtocol.ToString() },
            new[] { "Server certificate validated", config.Tls.ValidateServerCertificate ? "Yes" : "No (see warning above)" },
            new[] { "Client certificate", DescribeCertificate(config.Certificate.Kind) },
        };

        SimpleTableRenderer.DrawTable(ctx, ["Setting", "Value"], rows, [0.42, 0.58]);
        ctx.CursorY += 10;

        if (config.Headers.Count > 0)
        {
            var headerFont = ReportFonts.Bold(10);
            ctx.EnsureSpace(18);
            ctx.Gfx.DrawString("Request headers", headerFont, PdfTheme.BodyBrush, new XRect(ctx.MarginLeft, ctx.CursorY, ctx.ContentWidth, 16), XStringFormats.TopLeft);
            ctx.CursorY += 20;

            var headerRows = config.Headers
                .Select(h => new[] { h.Key, SensitiveHeaderNames.Contains(h.Key) ? "•••• (masked)" : h.Value })
                .ToList();
            SimpleTableRenderer.DrawTable(ctx, ["Header", "Value"], headerRows, [0.35, 0.65]);
            ctx.CursorY += 10;
        }

        if (!string.IsNullOrWhiteSpace(config.BodyTemplate))
        {
            var headerFont = ReportFonts.Bold(10);
            var bodyFont = ReportFonts.Monospace(8.5);
            ctx.EnsureSpace(18);
            ctx.Gfx.DrawString("Request body template", headerFont, PdfTheme.BodyBrush, new XRect(ctx.MarginLeft, ctx.CursorY, ctx.ContentWidth, 16), XStringFormats.TopLeft);
            ctx.CursorY += 18;

            var preview = config.BodyTemplate.Length > 600 ? config.BodyTemplate[..600] + " ...(truncated)" : config.BodyTemplate;
            var lines = WrapText(ctx.Gfx, preview, bodyFont, ctx.ContentWidth);
            ctx.EnsureSpace(lines.Count * 12 + 6);
            foreach (var line in lines)
            {
                ctx.Gfx.DrawString(line, bodyFont, PdfTheme.MutedBrush, new XRect(ctx.MarginLeft, ctx.CursorY, ctx.ContentWidth, 12), XStringFormats.TopLeft);
                ctx.CursorY += 12;
            }
            ctx.Gfx.DrawString("Note: {{guid}}, {{seq}}, {{timestamp}} tokens above were substituted with unique values per request.",
                ReportFonts.Italic(8), PdfTheme.MutedBrush, new XRect(ctx.MarginLeft, ctx.CursorY, ctx.ContentWidth, 14), XStringFormats.TopLeft);
            ctx.CursorY += 20;
        }
    }

    private static void DrawResultsOverview(PdfReportContext ctx, TestSummary summary)
    {
        DrawSectionHeading(ctx, "Results Overview");

        var rows = new List<string[]>
        {
            new[] { "Total requests", summary.TotalRequests.ToString("N0") },
            new[] { "Successful", $"{summary.SuccessCount:N0} ({summary.SuccessRate:P1})" },
            new[] { "Failed", $"{summary.ErrorCount:N0} ({1 - summary.SuccessRate:P1})" },
            new[] { "Overall throughput", $"{summary.OverallRequestsPerSecond:0.##} req/s" },
            new[] { "Total data received", FormatBytes(summary.TotalResponseBytes) },
            new[] { "Min latency", $"{summary.Latency.MinMs:0.#} ms" },
            new[] { "Average latency", $"{summary.Latency.AvgMs:0.#} ms" },
            new[] { "Median (P50) latency", $"{summary.Latency.MedianMs:0.#} ms" },
            new[] { "P90 latency", $"{summary.Latency.P90Ms:0.#} ms" },
            new[] { "P95 latency", $"{summary.Latency.P95Ms:0.#} ms" },
            new[] { "P99 latency", $"{summary.Latency.P99Ms:0.#} ms" },
            new[] { "Max latency", $"{summary.Latency.MaxMs:0.#} ms" },
        };

        SimpleTableRenderer.DrawTable(ctx, ["Metric", "Value"], rows, [0.5, 0.5]);
        ctx.CursorY += 10;
    }

    private static void DrawChartSection(PdfReportContext ctx, string heading, byte[] pngBytes)
    {
        DrawSectionHeading(ctx, heading);

        using var imageStream = new MemoryStream(pngBytes);
        using var image = PdfSharp.Drawing.XImage.FromStream(imageStream);
        var aspect = image.PixelHeight / (double)image.PixelWidth;
        var drawWidth = ctx.ContentWidth;
        var drawHeight = drawWidth * aspect;

        ctx.EnsureSpace(drawHeight + 10);
        ctx.Gfx.DrawImage(image, ctx.MarginLeft, ctx.CursorY, drawWidth, drawHeight);
        ctx.CursorY += drawHeight + 16;
    }

    private static void DrawErrorBreakdown(PdfReportContext ctx, TestSummary summary)
    {
        DrawSectionHeading(ctx, "Error Breakdown");

        if (summary.StatusCodeCounts.Any(kv => kv.Key >= 400))
        {
            var statusRows = summary.StatusCodeCounts
                .Where(kv => kv.Key >= 400)
                .OrderByDescending(kv => kv.Value)
                .Select(kv => new[] { kv.Key.ToString(), kv.Value.ToString("N0"), (kv.Value / (double)summary.TotalRequests).ToString("P1") })
                .ToList();
            SimpleTableRenderer.DrawTable(ctx, ["HTTP Status", "Count", "% of Total"], statusRows, [0.33, 0.33, 0.34]);
            ctx.CursorY += 10;
        }

        if (summary.ErrorTypeCounts.Count > 0)
        {
            var errorRows = summary.ErrorTypeCounts
                .OrderByDescending(kv => kv.Value)
                .Select(kv => new[] { kv.Key, kv.Value.ToString("N0"), (kv.Value / (double)summary.TotalRequests).ToString("P1") })
                .ToList();
            SimpleTableRenderer.DrawTable(ctx, ["Exception / Failure Type", "Count", "% of Total"], errorRows, [0.5, 0.25, 0.25]);
            ctx.CursorY += 10;
        }
    }

    private static void DrawAppendix(PdfReportContext ctx, TestSummary summary)
    {
        DrawSectionHeading(ctx, "Appendix: Methodology & Notes");

        var notes = new[]
        {
            "This report reflects a single-endpoint constant-load test: a fixed number of concurrent virtual " +
            "users issuing requests continuously for the configured duration or request budget. It does not " +
            "model ramp-up, spike, or sustained-endurance (soak) behavior, and does not represent a mixed, " +
            "production-realistic traffic pattern.",
            "Latency percentiles are computed using the nearest-rank method over all completed requests in the run.",
            "Throughput figures reflect what the client observed, including local network conditions between " +
            "the testing machine and the target endpoint.",
            $"Report generated by API Load Tester {AppVersion()}. The complete per-request raw data for this " +
            "run is available in the accompanying CSV export."
        };

        var font = ReportFonts.Regular(9.5);
        foreach (var note in notes)
        {
            var lines = WrapText(ctx.Gfx, "• " + note, font, ctx.ContentWidth);
            ctx.EnsureSpace(lines.Count * 13 + 8);
            foreach (var line in lines)
            {
                ctx.Gfx.DrawString(line, font, PdfTheme.BodyBrush, new XRect(ctx.MarginLeft, ctx.CursorY, ctx.ContentWidth, 13), XStringFormats.TopLeft);
                ctx.CursorY += 13;
            }
            ctx.CursorY += 6;
        }
    }

    private static void DrawSectionHeading(PdfReportContext ctx, string text)
    {
        ctx.EnsureSpace(34);
        var font = ReportFonts.Bold(14);
        ctx.Gfx.DrawString(text, font, PdfTheme.PrimaryBrush, new XRect(ctx.MarginLeft, ctx.CursorY, ctx.ContentWidth, 20), XStringFormats.TopLeft);
        ctx.CursorY += 20;
        ctx.Gfx.DrawLine(new XPen(PdfTheme.Primary, 1), ctx.MarginLeft, ctx.CursorY, ctx.MarginLeft + ctx.ContentWidth, ctx.CursorY);
        ctx.CursorY += 12;
    }

    private static void DrawWarningBanner(PdfReportContext ctx, string text)
    {
        var font = ReportFonts.Bold(9.5);
        var lines = WrapText(ctx.Gfx, text, font, ctx.ContentWidth - 16);
        var height = (lines.Count * 13) + 12;

        ctx.EnsureSpace(height + 8);
        var rect = new XRect(ctx.MarginLeft, ctx.CursorY, ctx.ContentWidth, height);
        ctx.Gfx.DrawRectangle(new XSolidBrush(XColor.FromArgb(0xFF, 0xF3, 0xE0)), rect);
        ctx.Gfx.DrawRectangle(new XPen(PdfTheme.Warning, 1), rect);

        var y = ctx.CursorY + 6;
        foreach (var line in lines)
        {
            ctx.Gfx.DrawString(line, font, PdfTheme.WarningBrush, new XRect(ctx.MarginLeft + 8, y, ctx.ContentWidth - 16, 13), XStringFormats.TopLeft);
            y += 13;
        }

        ctx.CursorY += height + 12;
    }

    private static void DrawPageFooters(PdfDocument document)
    {
        var font = ReportFonts.Regular(8);
        for (var i = 0; i < document.PageCount; i++)
        {
            var page = document.Pages[i];
            using var gfx = XGraphics.FromPdfPage(page, XGraphicsPdfPageOptions.Append);
            var text = $"Page {i + 1} of {document.PageCount} — API Load Tester Capacity Report";
            gfx.DrawString(text, font, PdfTheme.MutedBrush,
                new XRect(40, page.Height.Point - 28, page.Width.Point - 80, 16), XStringFormats.CenterRight);
        }
    }

    private static string DescribeCertificate(CertificateSourceKind kind) => kind switch
    {
        CertificateSourceKind.PfxFile => "Client certificate (.pfx file)",
        CertificateSourceKind.WindowsStore => "Client certificate (Windows certificate store)",
        _ => "None"
    };

    private static string FormatDuration(TimeSpan ts) =>
        ts.TotalHours >= 1 ? $"{ts:h\\hmm\\mss\\s}" : ts.TotalMinutes >= 1 ? $"{ts:m\\mss\\s}" : $"{ts.TotalSeconds:0.#}s";

    private static string FormatBytes(long bytes)
    {
        string[] units = ["B", "KB", "MB", "GB"];
        double value = bytes;
        var unit = 0;
        while (value >= 1024 && unit < units.Length - 1)
        {
            value /= 1024;
            unit++;
        }
        return $"{value:0.##} {units[unit]}";
    }

    private static List<string> WrapText(XGraphics gfx, string text, XFont font, double maxWidth)
    {
        var words = text.Split(' ');
        var lines = new List<string>();
        var current = "";

        foreach (var word in words)
        {
            var candidate = current.Length == 0 ? word : current + " " + word;
            if (gfx.MeasureString(candidate, font).Width > maxWidth && current.Length > 0)
            {
                lines.Add(current);
                current = word;
            }
            else
            {
                current = candidate;
            }
        }
        if (current.Length > 0)
            lines.Add(current);

        return lines;
    }

    private static string AppVersion() =>
        Assembly.GetExecutingAssembly().GetName().Version?.ToString(3) ?? "1.0.0";
}
